"""Add last_faucet_claim column to campnetwork

Revision ID: b22f609e176e
Revises: fa21a73bcae6
Create Date: 2025-07-09 13:51:35.731278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b22f609e176e'
down_revision: Union[str, None] = 'fa21a73bcae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campnetwork', sa.Column('faucet_last_claim', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campnetwork', 'faucet_last_claim')
    # ### end Alembic commands ###
