"""Add account_blocked column to campnetwork

Revision ID: fa21a73bcae6
Revises: 86c4a91e69a7
Create Date: 2025-07-02 19:58:05.382571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa21a73bcae6'
down_revision: Union[str, None] = '86c4a91e69a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campnetwork', sa.Column('account_blocked', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campnetwork', 'account_blocked')
    # ### end Alembic commands ###
